### ISSUE TITLE
SharedClasses.SCM23.MultiThread_0 excessive duration

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-systemtest#103]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_ppc64_aix_Nightly/171
`08:31:24  Running test SharedClasses.SCM23.MultiThread_0`
`09:37:20  MT1 08:36:31 >> Loaded 19000 classes...`

Seems https://github.com/eclipse/openj9-systemtest/pull/99 isn't working properly.

**Comment by pshipton** [comment]
@Mesbah-Alam

**Comment by pshipton** [comment]
There is also a timeout reported in https://github.com/eclipse/openj9/issues/7489, which shouldn't have occurred.

**Comment by pshipton** [comment]
> Do you suggest we add a max value for SharedClasses.SCM23.MultiThread_0 test (e.g. in LoaderSlaveMultiThread.java) as well?

Yes. The tests is running for multiple hours, which is excessive. If there are other variants doing the same, they should be limited as well.

**Comment by pshipton** [comment]
@Mesbah-Alam any outlook for this? The Windows machines are backlogged due to this problem.

**Comment by Mesbah-Alam** [comment]
https://github.com/eclipse/openj9-systemtest/pull/105 should fix this. I'll ask for a review after the test finishes.
