### ISSUE TITLE
Excessive duration of system tests

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-systemtest#104]
The following system tests are running too long for the nightly builds, and should be configured to run a smaller load.

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_windows_Nightly/487

ClassLoadingTest_special_26
-Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation

ClassLoadingTest_special_27
-Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation

**Comment by pshipton** [comment]
@Mesbah-Alam

**Comment by Mesbah-Alam** [comment]
https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/306 should fix this.
