### ISSUE TITLE
playlist.xml:30:55: The entity name must immediately follow the '&' in the entity reference

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-systemtest#107]
The problem is intermittent for some reason.
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_s390x_linux_xl_Nightly/40
```
10:03:11  Generating make file /home/jenkins/jenkins-agent/workspace/Test_openjdk8_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/../system/openj9-systemtest/openj9.build/autoGen.mk
10:03:11  [Fatal Error] playlist.xml:30:55: The entity name must immediately follow the '&' in the entity reference.
10:03:11  org.xml.sax.SAXParseException; systemId: file:/home/jenkins/jenkins-agent/workspace/Test_openjdk8_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/../system/openj9-systemtest/openj9.build/playlist.xml; lineNumber: 30; columnNumber: 55; The entity name must immediately follow the '&' in the entity reference.
10:03:11  	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
10:03:11  	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
10:03:11  	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
10:03:11  	at org.testKitGen.MkGen.processPlaylist(MkGen.java:100)
10:03:11  	at org.testKitGen.MkGen.start(MkGen.java:67)
10:03:11  	at org.testKitGen.MkTreeGen.traverse(MkTreeGen.java:78)
10:03:11  	at org.testKitGen.MkTreeGen.traverse(MkTreeGen.java:69)
10:03:11  	at org.testKitGen.MkTreeGen.traverse(MkTreeGen.java:69)
10:03:11  	at org.testKitGen.MkTreeGen.traverse(MkTreeGen.java:69)
10:03:11  	at org.testKitGen.MkTreeGen.start(MkTreeGen.java:27)
10:03:11  	at org.testKitGen.MainRunner.start(MainRunner.java:29)
10:03:11  	at org.testKitGen.MainRunner.main(MainRunner.java:23)
10:03:11  makeGen.mk:39: recipe for target 'autogen' failed
```

**Comment by pshipton** [comment]
Keith W. Campbell  5 hours ago
It’s complaining (reasonably) about:
```
		<command>cd $(OPENJ9_SYSTEMTEST_ROOT)/openj9.build && make test.DaaLoadTest_daa1 JAVA_ARGS=$(Q)$(JVM_OPTIONS)$(Q); \
		$(TEST_STATUS)</command>
```
Each `&` should be written as `&amp;`.

**Comment by pshipton** [comment]
Henry Zongaro  37 minutes ago
This error has been reported before - most recently on October 10 of last year.  I don’t know why the error is only occurring intermittently, but the playlist.xml is definitely not well-formed XML.  As Keith said, the ampersands should be written as `&amp;`.

**Comment by llxia** [comment]
https://github.com/eclipse/openj9-systemtest/blob/master/openj9.build/playlist.xml is very old. Usages like `<tag>` and `<subset>SE80</subset>` are no longer supported in TKG. 

Most importantly, we do not use this playlist when running system tests. All system playlist files should be in https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/system

I suspect this file was added as part of the initial setup and never got cleaned up. If so, we can simply delete this file. @Mesbah-Alam Could you please confirm? Thanks

**Comment by Mesbah-Alam** [comment]
@llxia : [this](https://github.com/eclipse/openj9-systemtest/pull/110) removes it. Please review.

**Comment by llxia** [comment]
Close this issue as the file is removed.
