### ISSUE TITLE
DaaAll test timeouts are too long

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9-systemtest#121]
The DaaAll timeouts: https://github.com/eclipse/openj9-systemtest/blob/5742d2202a76e974e224fa95dd70914fb84712af/openj9.test.load/src/test.load/net/openj9/stf/DaaLoadTest.java#L55
are currently set to 15 hours, which far exceeds the AdoptOpenJDK Jenkins 10hour job time limit. This has consequences for job Abort and hung Java processes.
Given DaaAll normally runs in 1min, these values seem excessive?

**Comment by andrew-m-leonard** [comment]
@Mesbah-Alam these timeouts seem quite excessive and mean if a problem occurs and a test fails after 1min, like has happened with https://github.com/eclipse/openj9/issues/11616 then the test waits 15hours before timing out. In the case at AdoptOpenJDK we Abort the job and this potentially leaves hung Java processes...

**Comment by Mesbah-Alam** [comment]
@andrew-m-leonard - I agree. `15h` is an impractical timeout value. We have another one with `20h` timeout : https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MathLoadTest.java#L37

I will create PRs to reduce these timeout values.

**Comment by andrew-m-leonard** [comment]
Thank you @Mesbah-Alam
