### ISSUE TITLE
Update to use STF

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9-systemtest#138]
System stf git repo is https://github.com/adoptium/STF.git (uppercase STF). We need to change the reference to uppercase STF:
https://github.com/eclipse-openj9/openj9-systemtest/blob/master/openj9.build/build.xml#L40

Related: adoptium/aqa-tests#2949

**Comment by xius666** [comment]
Can I take this?

**Comment by smlambert** [comment]
Yes @xius666 - please take it.
