### ISSUE TITLE
Add osx to the list of supported platforms in sharedClasses.jvmti makefile

### ISSUE THREAD

**Issue by mesbaha** [eclipse/openj9-systemtest#26]
Currently, the list of supported platforms in the sharedClasses.jvmti test does not include osx. We need to test this project compilation on osx and add necessary fixes to this makefile.

**Comment by Mesbah-Alam** [comment]
On a second thought, this is a non-issue, as we do not have openj9 builds for MacOS. If we get some in future, we can add support for it in the openj9 systemtests.
