### ISSUE TITLE
javax_platform property set to ppc on ppcle

### ISSUE THREAD

**Issue by lumpfish** [eclipse/openj9-systemtest#29]
openjdk.build/include/top.xml contains a macro `<get-platform-arch>` which appears to be returning ppc when executing on ppcle, even though the java.os.arch java system property is set correctly to ppcle.

Looking at the code, this may be the issue:
```
<condition property="@{property}" value="ppcle">
	<and>
		<contains string="@{arch}" substring="ppcle"/>
	</and>
</condition>
<condition property="@{property}" value="ppc">
	<and>
		<contains string="@{arch}" substring="ppc"/>
	</and>
</condition>
```
The second match for 'ppc' is true whether the arch is 'ppc' or 'ppcle', so the code to set the property to 'ppc' will be run in both cases.  What is puzzling though is that I thought properties in ant were immutable, so the setting the property a second time would have no effect.  Perhaps setting a property via a macro in this way means that is not true?
We can test this by reversing the two conditions - check for ppc first and then for ppcle.
@Mesbah-Alam - do you have a test environment you could check this theory out on?

**Comment by Mesbah-Alam** [comment]
Yes, I'll test and report back!

**Comment by Mesbah-Alam** [comment]
It didn't resolve the issue: https://urv-jenkins.canlab.ibm.com:9095/view/SV_Tests/job/test.personal/246/console

**Comment by lumpfish** [comment]
The error was actually that java.os.arch contains ppc64le on this platform, not ppcle, so the check was incorrect.  The ant property was immutable as expected.

**Comment by Mesbah-Alam** [comment]
As found out in the test, the only change needed was 

```
<condition property="@{property}" value="ppcle">
	<and>
		<contains string="@{arch}" substring="ppc64le"/>
	</and>
</condition>
```

as os.arch contains ppc64le, not ppcle.
