### ISSUE TITLE
LOGDIR doesn't appear to be working for these tests

### ISSUE THREAD

**Issue by sxa555** [eclipse/openj9-systemtest#3]
My CI job https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk9j9_stf_systemtests-all/ doesn't appear to be working properly - it's acting as though the LOGDIR variable isn't being processed so the TAP output isn't being generated properly (there are failing tests despite the jobs being green.

Opening this so I remember to look into it ;-)

**Comment by Mesbah-Alam** [comment]
@sxa555 - Do you still need this issue?

**Comment by sxa555** [comment]
On the basis that the referenced job no longer exists and another harness is executing them I'm going to close this
