### ISSUE TITLE
openj9.test.sharedClasses.jvmti fails to build on Windows

### ISSUE THREAD

**Issue by Mesbah-Alam** [eclipse/openj9-systemtest#38]
openj9.test.sharedClasses.jvmti fails to build on Windows

Fails with: 

```
16:23:34      [exec] '/RTC1' is not recognized as an internal or external command
```
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_system/job/Grinder/205/console

We need to find out why we are using /RTC1 flag in the compilation of natives in /openj9.test.sharedClasses.jvmti/src/native/Makefile

```
CFLAGS=/DWIN32 /D_WINDOWS -Gy /LD /Zi /Odi /c /RTC1 /Fo"$(OBJDIR)/sharedClasses$(OSUFFIX)" /Fd"$(OBJDIR)"
```

**Comment by Mesbah-Alam** [comment]
I tried removing the /RTC1 flag, but it gives the following error now: 

```
11:57:32 build-natives-windows:
11:57:32      [exec] 
11:57:32      [exec] C:\Users\j9build\j9build\workspace\Grinder\openjdk-tests\systemtest\openj9-systemtest\openj9.test.sharedClasses.jvmti>call "c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" amd64   && make -C C:\Users\j9build\j9build\workspace\Grinder\openjdk-tests\systemtest\openj9-systemtest\openj9.test.sharedClasses.jvmti/src/native SRCDIR=C:\Users\j9build\j9build\workspace\Grinder\openjdk-tests\systemtest\openj9-systemtest\openj9.test.sharedClasses.jvmti/src/native PLATFORM=win_x86-64 JAVA_HOME=C:\Users\j9build\j9build\workspace\Grinder\openjdkbinary\j2sdk-image\jre\ OUTDIR=C:\Users\j9build\j9build\workspace\Grinder\openjdk-tests\systemtest\openj9-systemtest\openj9.test.sharedClasses.jvmti/bin/native 
11:57:32      [exec] Setting environment for using Microsoft Visual Studio 2010 x64 tools.
11:57:33      [exec] make[1]: Entering directory '/cygdrive/c/Users/j9build/j9build/workspace/Grinder/openjdk-tests/systemtest/openj9-systemtest/openj9.test.sharedClasses.jvmti/src/native'
11:57:33      [exec] mkdir C:\\Users\\j9build\\j9build\\workspace\\Grinder\\openjdk-tests\\systemtest\\openj9-systemtest\\openj9.test.sharedClasses.jvmti\\bin\\native\\win_x86-64
11:57:33      [exec] Microsoft Windows [Version 6.3.9600]
11:57:33      [exec] (c) 2013 Microsoft Corporation. All rights reserved.
11:57:33      [exec] 
11:57:33      [exec] C:\Users\j9build\j9build\workspace\Grinder\openjdk-tests\systemtest\openj9-systemtest\openj9.test.sharedClasses.jvmti\src\native>cl /DWIN32 /D_WINDOWS -Gy /LD /Zi /Odi /c /Fo"C:\\Users\\j9build\\j9build\\workspace\\Grinder\\openjdk-tests\\systemtest\\openj9-systemtest\\openj9.test.sharedClasses.jvmti\\bin\\native\\win_x86-64/sharedClasses.obj" /Fd"C:\\Users\\j9build\\j9build\\workspace\\Grinder\\openjdk-tests\\systemtest\\openj9-systemtest\\openj9.test.sharedClasses.jvmti\\bin\\native\\win_x86-64" /I. /I"../../../lib/native/jvmti" /I"C:\Users\j9build\j9build\workspace\Grinder\openjdkbinary\j2sdk-image\jre\/../include" /I"C:\Users\j9build\j9build\workspace\Grinder\openjdkbinary\j2sdk-image\jre\/../include/win32" /I"C:\Users\j9build\j9build\workspace\Grinder\openjdkbinary\j2sdk-image\jre\/include" /I"C:\Users\j9build\j9build\workspace\Grinder\openjdkbinary\j2sdk-image\jre\/include/win32" C:\Users\j9build\j9build\workspace\Grinder\openjdk-tests\systemtest\openj9-systemtest\openj9.test.sharedClasses.jvmti/src/native/sharedClasses.c
11:57:33      [exec] make[1]: Leaving directory '/cygdrive/c/Users/j9build/j9build/workspace/Grinder/openjdk-tests/systemtest/openj9-systemtest/openj9.test.sharedClasses.jvmti/src/native'
11:57:33      [exec] '/Fo\"C:\\Users\\j9build\\j9build\\workspace\\Grinder\\openjdk-tests\\systemtest\\openj9-systemtest\\openj9.test.sharedClasses.jvmti\\bin\\native\\win_x86-64/sharedClasses.obj\"' is not recognized as an internal or external command,
11:57:33      [exec] operable program or batch file.
11:57:33      [exec] make[1]: *** [Makefile:214: C:\\Users\\j9build\\j9build\\workspace\\Grinder\\openjdk-tests\\systemtest\\openj9-systemtest\\openj9.test.sharedClasses.jvmti\\bin\\native\\win_x86-64/sharedClasses.obj] Error 1
11:57:33 
11:57:33 BUILD FAILED

```
(tested in internal Grinder on a cloud Windows Machine). 

@lumpfish - would you know, off the top of your head, why `sharedClasses.c` is failing to compile on these Windows cloud machines? Obviously these environments are different somewhere or the other than the original environment on which the script was tested, details: https://github.com/eclipse/openj9-systemtest/blob/331835bd9bd3671eb7c9c50811b07d60023b3fc2/openj9.test.sharedClasses.jvmti/src/native/Makefile#L153

Since this issue is blocking Windows testing for openj9, we are tempted to have this native test excluded if we can't figure out how to build it any time soon.

**Comment by lumpfish** [comment]
What environment are you running this in?
The build has been tested with the gnu make windows port (example -version output below) running in a Windows environment (cmd.exe) - i.e. in a 'real' Windows environment.
If you are running under cygwin with the cygwin tool chain (e.g. cygwin gnu make) I wouldn't be surprised if there were issues.
What I would not want to have to do is install cygwin on a Windows machine just to run some tests.
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-pc-mingw32
```

**Comment by smlambert** [comment]
The goal of @Mesbah-Alam 's enquiry is to see whether we can run tests in both the 'real' Windows environment (which we know it does), AND a cygwin environment (required env for compiling the SDK binaries), in which we find ourselves in all of the open projects where we are using these tests. 

I have advised Mesbah to temporarily disable this native sub-test on Windows to unblock us from turning the remaining tests on at the Eclipse OpenJ9 project, until we can get it to compile in the cygwin scenario (which we need to be able to do).

**Comment by Mesbah-Alam** [comment]
The issue is seen on a Windows cloud machine which is indeed running cygwin gnu make:  

```
$ make --version
GNU Make 4.2.1
Built for x86_64-unknown-cygwin
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I am going to exclude the test temporarily to unblock the OpenJ9 builds, as additional work is needed to get the test (SharedClassesAPI)  working on Cygwin environment.

**Comment by llxia** [comment]
Thanks @Mesbah-Alam !

**Comment by Mesbah-Alam** [comment]
This PR excludes the failing sharedClasses.jvmti test: https://github.com/eclipse/openj9-systemtest/pull/40

There however are test failures: 

```
11:10:34 Can't locate stf/stfUtility.pm in @INC (you may need to install the stf::stfUtility module) (@INC contains: /cygdrive/c/Users/jenkins/workspace/Grinder /usr/local/lib/perl5/site_perl/5.26/x86_64-cygwin-threads /usr/local/share/perl5/site_perl/5.26 /usr/lib/perl5/vendor_perl/5.26/x86_64-cygwin-threads /usr/share/perl5/vendor_perl/5.26 /usr/lib/perl5/5.26/x86_64-cygwin-threads /usr/share/perl5/5.26) at C:/Users/jenkins/workspace/Grinder/openjdk-tests///..//jvmtest\systemtest\stf\stf.core\scripts\stf.pl line 30.
11:10:34 BEGIN failed--compilation aborted at C:/Users/jenkins/workspace/Grinder/openjdk-tests///..//jvmtest\systemtest\stf\stf.core\scripts\stf.pl line 30.
```
I'll run a separate build with full list of systemtests on Windows to flush out other potential failures. But the above PR can be used to get at least the compilation to work on Windows.

**Comment by lumpfish** [comment]
If you're running cygwin perl rather than Strawberry perl, then there will likely be issues with that too.

**Comment by Mesbah-Alam** [comment]
Lots of other tests are actually failing due to ```Can't locate stf/stfUtility.pm in @INC (you may need to install the stf::stfUtility module) ```

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/136/console

I suspect this is due to the environment using the Perl from Cygwin as opposed to Strawberry Perl-- as Simon mentioned above.

**Comment by Mesbah-Alam** [comment]
This has been fixed via https://github.com/eclipse/openj9-systemtest/issues/61

SharedClassesAPI test is working fine on Windows now https://ci.eclipse.org/openj9/view/Test/job/Test-extended.system-JDK8-win_x86/198/tapResults/
