### ISSUE TITLE
Test-sanity.system-JDK11-win_x86-64_cmprssptrs fails to build '/RTC1' is not recognized

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-systemtest#61]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-win_x86-64_cmprssptrs/109
```
00:54:57      [exec] C:\Users\jenkins\workspace\Test-sanity.system-JDK11-win_x86-64_cmprssptrs\openjdk-tests\systemtest\openjdk-systemtest\openjdk.test.modularity\src\tests\com.test.jlink\native>cl /DWIN32 /D_WINDOWS -Gy /LD /Zi /Odi /c /RTC1 /Fo"C:\\Users\\jenkins\\workspace\\Test-sanity.system-JDK11-win_x86-64_cmprssptrs\\openjdk-tests\\systemtest\\openjdk-systemtest\\openjdk.test.modularity\\bin\\tests\\com.test.jlink\\native\\lib\\win_x86-64/JniTest.obj" /Fd"C:\\Users\\jenkins\\workspace\\Test-sanity.system-JDK11-win_x86-64_cmprssptrs\\openjdk-tests\\systemtest\\openjdk-systemtest\\openjdk.test.modularity\\bin\\tests\\com.test.jlink\\native\\lib\\win_x86-64/win_x86-64" /I. /I"C:\Users\jenkins\workspace\Test-sanity.system-JDK11-win_x86-64_cmprssptrs\openjdk-tests\systemtest\openjdk-systemtest/openjdk.test.modularity/bin/tests/com.test.jlink/native/lib" /I"C:\Users\jenkins\workspace\Test-sanity.system-JDK11-win_x86-64_cmprssptrs\openjdkbinary\j2sdk-image\/../include" /I"C:\Users\jenkins\workspace\Test-sanity.system-JDK11-win_x86-64_cmprssptrs\openjdkbinary\j2sdk-image\/../include/win32" /I"C:\Users\jenkins\workspace\Test-sanity.system-JDK11-win_x86-64_cmprssptrs\openjdkbinary\j2sdk-image\/include" /I"C:\Users\jenkins\workspace\Test-sanity.system-JDK11-win_x86-64_cmprssptrs\openjdkbinary\j2sdk-image\/include/win32" JniTest.c
00:54:57      [exec] make[1]: Leaving directory '/cygdrive/c/Users/jenkins/workspace/Test-sanity.system-JDK11-win_x86-64_cmprssptrs/openjdk-tests/systemtest/openjdk-systemtest/openjdk.test.modularity/src/tests/com.test.jlink/native'
00:54:57      [exec] makefile:199: JAVA_EXECUTABLE set to 
00:54:57      [exec] '/RTC1' is not recognized as an internal or external command,
00:54:57      [exec] operable program or batch file.
00:54:57      [exec] make[1]: *** [makefile:226: C:\\Users\\jenkins\\workspace\\Test-sanity.system-JDK11-win_x86-64_cmprssptrs\\openjdk-tests\\systemtest\\openjdk-systemtest\\openjdk.test.modularity\\bin\\tests\\com.test.jlink\\native\\lib\\win_x86-64/JniTest.obj] Error 1
```

**Comment by pshipton** [comment]
@Mesbah-Alam @smlambert

**Comment by pshipton** [comment]
Also in https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-win_x86-64_cmprssptrs/108

**Comment by Mesbah-Alam** [comment]
This fell through as Modularity was only tested on Linux, not on Windows. 

It looks like cygwin environment is not liking how the flags are set for Windows in the modularity native build makefile : https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/3ecd31f0333c0f91e7f5d108a2f71fd49ad4f1f6/openjdk.test.modularity/src/tests/com.test.jlink/native/makefile#L137

/RTC1 is used in sharedClasses.jvmti tests as well, and it works fine there (runs on jdk8 windows system test builds. https://github.com/eclipse/openj9-systemtest/blob/5b31a568383930d68c82aafd25fa34e13302df55/openj9.test.sharedClasses.jvmti/src/native/Makefile#L194

I can't quite figure out why it's not working for the modularity tests. Need to investigate further.

**Comment by Mesbah-Alam** [comment]
Will exclude the modularity tests from building and running on Windows temporarily - so that the jdk11 windows systemtest builds can be unblocked.

**Comment by Mesbah-Alam** [comment]
Problem with '/RTC1' flag was seen before as well, with sharedClasses.jvmti test:  https://github.com/eclipse/openj9-systemtest/issues/38

- We had excluded the test and concentrated on fixing the other cygwin related failures. 

Now that we have got the system tests running on Windows (we are using strawberry perl), we should figure out why /RTC1 is causing issue still.

@lumpfish - please comment.

**Comment by lumpfish** [comment]
I've submitted PR https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/217 to fix this.

**Comment by Mesbah-Alam** [comment]
Modularity tests are building fine and running on Windows builds now after Simon's fix: https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-win_x86-64_cmprssptrs/141/tapResults/

@pshipton - Could we close this issue now?

**Comment by pshipton** [comment]
Thanks. The problem no longer occurs in the OpenJ9 builds.
