### ISSUE TITLE
Git clone URLs to be corrected in the README

### ISSUE THREAD

**Issue by sabkrish** [eclipse/openj9-systemtest#7]
1) 
Currently, the git clone URLs look like this.
git clone git@github.com/AdoptOpenJDK/stf.git stf

This fails with the message "fatal: repository 'git@github.com/AdoptOpenJDK/stf.git' does not exist".

The command should read git clone git@github.com:AdoptOpenJDK/stf.git stf 

It should be ":" after github.com instead of "/". 
This applies to all the git URLs. I've just given one as example above.

2)
Instead of this,
git clone git@github.com/eclipse/openj9/openj9-systemtest.git openj9-systemtest

It should read
git clone git@github.com:eclipse/openj9-systemtest.git openj9-systemtest

**Comment by samkamer** [comment]
Contributors (especially new comers) may miss the 'ssh' requirements for using the proposed URL format. So either we should add that also to the readme with this change or simply put the correct URL for using https

**Comment by Mesbah-Alam** [comment]
@sabkrish Can this PR be closed (by https://github.com/eclipse/openj9-systemtest/pull/8) ?
