### ISSUE TITLE
sanity.system failing to build on osx

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-systemtest#72]
Seems like a missing space issue again
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-osx_x86-64_cmprssptrs/49
osx1011-x86-1
```
03:08:11      [exec] ld: unknown option: -o/Users/jenkins/workspace/Test-sanity.system-JDK11-osx_x86-64_cmprssptrs/openjdk-tests/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/tests/com.test.jlink/native/bin/osx_x86-64/libJniTest.so
03:08:11      [exec] collect2: ld returned 1 exit status
```

Likely related to https://github.com/eclipse/openj9/issues/4078

**Comment by pshipton** [comment]
@Mesbah-Alam

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-osx_x86-64_cmprssptrs/50
osx1011-x86-1
```
03:44:36      [exec] ld: unknown option: -o/Users/jenkins/workspace/Test-extended.system-JDK11-osx_x86-64_cmprssptrs/openjdk-tests/systemtest/openjdk-systemtest/openjdk.test.modularity/bin/tests/com.test.jlink/native/bin/osx_x86-64/libJniTest.so
```

**Comment by pshipton** [comment]
I would set a blocker label on this if there was one.

**Comment by Mesbah-Alam** [comment]
The [makefile](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.modularity/src/tests/com.test.jlink/native/makefile) hasn't been touched recently. I am a bit confused why it had been passing and just started to fail in this latest build.

**Comment by Mesbah-Alam** [comment]
Just noticed, yes, it should be related to https://github.com/eclipse/openj9/issues/4078

**Comment by pshipton** [comment]
@Mesbah-Alam can this be fixed asap please. It consistently blocks the Test-sanity.system-JDK11-osx build.

**Comment by pshipton** [comment]
@Mesbah-Alam it is due to eclipse/openj9#4078 however since that is not being fixed soon, last time we had this problem it was fixed to add a space when building the system tests.

**Comment by Mesbah-Alam** [comment]
@pshipton : the space was added in the makefile that fails to execute on `osx1011-x86-1`: https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/220 

Hope this fixes it!

**Comment by pshipton** [comment]
Thanks. I'll go ahead and close this, will reopen if the problem is seen again.
