### ISSUE TITLE
Disable system test modes running -Xint

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9-systemtest#95]
Running the system tests with -Xint is way too slow. We don't need to run these modes on a regular basis, they can be disabled and available to run manually.
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Personal/31

DaaLoadTest_daa1_special_19
11:09:52  variation: Mode550
11:09:52  JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xint -Xgcpolicy:balanced 
13:26:09  DLT 17:26:08.430 - Load test completed

DaaLoadTest_daa2_special_19
14:44:24  variation: Mode550
14:44:24  JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xint -Xgcpolicy:balanced 
15:23:54  DLT 19:23:52.247 - Load test completed

DaaLoadTest_daa3_special_19
16:27:26  variation: Mode550
16:27:26  JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xint -Xgcpolicy:balanced 
16:30:44  DLT 20:30:43.678 - Load test completed

DaaLoadTest_all_special_19
16:45:29  variation: Mode550
16:45:29  JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xint -Xgcpolicy:balanced 
18:02:19  DLT 22:02:17.755 - Completed 38.6%. Number of tests started=2781 (+0)

**Comment by pshipton** [comment]
@smlambert @Mesbah-Alam

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9/issues/6992#issuecomment-529150893 may be part of the problem but we can still disable the -Xint modes to get through the system testing faster.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_special.system_x86-64_windows_Personal/2
DaaLoadTest_all_special_32 
16:16:15  variation: Mode610-OSRG
16:16:15  JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation -Xgcpolicy:gencon 
18:18:34  DLT 17:19:15.554 - Completed 97.0%. Number of tests started=6986 (+2)

This one is also quite slow to run, can we do something to configure how long it runs to reduce the overall system testing time?

**Comment by Mesbah-Alam** [comment]
> We don't need to run these modes on a regular basis, they can be disabled and available to run manually

I can disable these tests from the playlists to permanently stop them from running in the automated build.

**Comment by pshipton** [comment]
FYI a system test run on JDK11, which resulted in a number of timeout problems.
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Special-System-JDK11/2/

ppcle 
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Personal/39/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Personal/40 - Daa Timeout has been exceeded

xLinux
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_Personal/1/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_Personal/2
- timeout while running DaaLoadTest_all_special_19 Mode 550

xLinux XL
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_xl_Personal/1/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_xl_Personal/5/ - MathLoadTest_bigdecimal_special_9 
13:12:17  variation: Mode113
13:12:17  JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:gencon -Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve -Xmn512k -Xnocompressedrefs 
**FAILED** Process MLT has timed out

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_xl_Personal/2/ - timeout while running DaaLoadTest_daa2_special_5 Mode109

**Comment by Mesbah-Alam** [comment]
```
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_xl_Personal/5/ - MathLoadTest_bigdecimal_special_9
13:12:17 variation: Mode113
13:12:17 JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:gencon -Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve -Xmn512k -Xnocompressedrefs
FAILED Process MLT has timed out
```
MathLoadTest for BigDecimal has a [timeout of 1 hour ](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/eee70bd5af4fb59e046d33d62218423ab938e73d/openjdk.test.load/src/test.load/net/adoptopenjdk/stf/MathLoadTest.java#L37)

These timeout values obviously weren't set based on the time they'd take if run with these special modes where -Xjit:count=0 would be used for example. We need to increase the timeout of these load tests based on the runtimes needed for these special modes.

**Comment by pshipton** [comment]
Or can we tune the tests to run less testing so it can complete within an hour? Running the testing for more than an hour seems excessive.

**Comment by Mesbah-Alam** [comment]
> Or can we tune the tests to run less testing so it can complete within an hour?

The loads in the tests (and their timeouts) have been calibrated according to regular test runs that happen across all platforms in system tests. We did not consider special modes involving -Xjit:count=0 etc that'd run much slower than normal. If we update all the load tests based on the performance of -Xjit:count=0 runs, then we might reduce the workload in system tests in regular runs -- something we may not want to do. 

From https://github.com/eclipse/openj9-systemtest/issues/95#issuecomment-529676932, it looks like the following tests need fail due to timeout: 

```
DaaLoadTest_all
DaaLoadTest_daa2
MathLoadTest_bigdecimal
```

We can start with reducing the worklaod in just these tests and see if this stabilizes the special mode runs. 

@pshipton

**Comment by pshipton** [comment]
Ideally the load should be reduced only for the slow modes.
It's also interesting the timeouts occurred only on JDK11, the JDK8 runs seem fine.

**Comment by Mesbah-Alam** [comment]
> Ideally the load should be reduced only for the slow modes.
It's also interesting the timeouts occurred only on JDK11, the JDK8 runs seem fine.

I concur. Testing out a change that'd allow tests to dynamically detect if special slow running jvm options are in use and switch to running a smaller load if true.

**Comment by pshipton** [comment]
This mode is still running slow. 
See also https://github.com/eclipse/openj9-systemtest/issues/95#issuecomment-529151462
```
09:00:52  variation: Mode107-OSRG
09:00:52  JVM_OPTIONS: -Xcompressedrefs -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation 
```
DaaLoadTest_all_special_24

**Comment by pshipton** [comment]
There is another -Xjit:count=0 timeout here 
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_xl_Personal/14
MathLoadTest_bigdecimal_special_6
[2019-09-15T15:13:53.068Z] variation: Mode113
[2019-09-15T15:13:53.068Z] JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:gencon -Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve -Xmn512k -Xnocompressedrefs

**Comment by pshipton** [comment]
Running slow
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_windows_Nightly/282
MathLoadTest_bigdecimal_special_27
07:45:34  variation: Mode612-OSRG
07:45:34  JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:gencon -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation

**Comment by Mesbah-Alam** [comment]
> https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Personal/49
DaaLoadTest_all_special_24

This seems to be taking about 20m - which we accepted last Friday. Should I reduce the load even more? 

I will reduce the workload on MathLoadTest_bigdecimal a bit more as it's timing out still (taking more than 1h) on certain platforms.

**Comment by pshipton** [comment]
There are multiple occurrences of `-Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation` running slow, I think we should reduce the load for this mode. If we get through the testing faster, we can enable more testing in the overnight runs.

**Comment by Mesbah-Alam** [comment]
> There are multiple occurrences of -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation running slow, I think we should reduce the load for this mode. If we get through the testing faster, we can enable more testing in the overnight runs.

This PR should fix this: https://github.com/eclipse/openj9-systemtest/pull/97

**Comment by pshipton** [comment]
Thanks Mesbah. Things are better, and I've stopped looking for slowness issues. I'll close this.

**Comment by pshipton** [comment]
DaaLoadTest_all_special_6 is still running slow, over an hour.
-Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_special.system_x86-64_linux_xl_Personal/26

**Comment by Mesbah-Alam** [comment]
> DaaLoadTest_all_special_6 is still running slow, over an hour.
-Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_special.system_x86-64_linux_xl_Personal/26

`-Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve` has been added to the list of jit options to be treated as "slow running" options in the DAA test in this PR https://github.com/eclipse/openj9-systemtest/pull/101 - this should solve the issue.
